export const pokemones = [
  {
    id: 3,
    nombre: "Venusaur",
    tipo: ["Planta", "Veneno"],
    altura: 2.0,
    peso: 100.0,
    generacion: 1,
    hp: 80,
    ataque: 82,
    velocidad: 80,
    defensa: 83,
    habilidad: "Espesura",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Raro",
    imagen: "./assets/img/venusaur.png",
    sonido: "./assets/sound/venusaur.mp3",
    shiny: true,
    imagenShiny: "./assets/img/venusaur-shiny.png",
  },

  {
    id: 6,
    nombre: "Charizard",
    tipo: ["Fuego", "Volador"],
    altura: 1.7,
    peso: 90.5,
    generacion: 1,
    hp: 78,
    ataque: 84,
    velocidad: 100,
    defensa: 78,
    habilidad: "Mar Llamas",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Raro",
    imagen: "./assets/img/charizard.png",
    sonido: "./assets/sound/charizard.mp3",
    shiny: true,
    imagenShiny: "./assets/img/charizard-shiny.png",
  },

  {
    id: 25,
    nombre: "Pikachu",
    tipo: ["Eléctrico"],
    altura: 0.4,
    peso: 6.0,
    generacion: 1,
    hp: 35,
    ataque: 55,
    velocidad: 90,
    defensa: 40,
    habilidad: "Electricidad Estática",
    tieneEvolucion: true,
    evolucion: "Raichu",
    nivelEvolucion: null,
    rareza: "Raro",
    imagen: "./assets/img/pikachu.png",
    sonido: "./assets/sound/pikachu.mp3",
    shiny: true,
    imagenShiny: "./assets/img/pikachu-shiny.png",
  },

  {
    id: 94,
    nombre: "Gengar",
    tipo: ["Fantasma", "Veneno"],
    altura: 1.5,
    peso: 40.5,
    generacion: 1,
    hp: 60,
    ataque: 65,
    velocidad: 110,
    defensa: 60,
    habilidad: "Cuerpo Maldito",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Raro",
    imagen: "./assets/img/gengar.png",
    sonido: "./assets/sound/gengar.mp3",
    shiny: true,
    imagenShiny: "./assets/img/gengar-shiny.png",
  },

  {
    id: 149,
    nombre: "Dragonite",
    tipo: ["Dragón", "Volador"],
    altura: 2.2,
    peso: 210.0,
    generacion: 1,
    hp: 91,
    ataque: 134,
    velocidad: 80,
    defensa: 95,
    habilidad: "Compensación",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Raro",
    imagen: "./assets/img/dragonite.png",
    sonido: "./assets/sound/dragonite.mp3",
    shiny: true,
    imagenShiny: "./assets/img/dragonite-shiny.png",
  },

  {
    id: 448,
    nombre: "Lucario",
    tipo: ["Lucha", "Acero"],
    altura: 1.2,
    peso: 54.0,
    generacion: 4,
    hp: 70,
    ataque: 110,
    velocidad: 90,
    defensa: 70,
    habilidad: "Foco Interno",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Raro",
    imagen: "./assets/img/lucario.png",
    sonido: "./assets/sound/lucario.mp3",
    shiny: true,
    imagenShiny: "./assets/img/lucario-shiny.png",
  },

  {
    id: 658,
    nombre: "Greninja",
    tipo: ["Agua", "Siniestro"],
    altura: 1.5,
    peso: 40.0,
    generacion: 6,
    hp: 72,
    ataque: 95,
    velocidad: 122,
    defensa: 67,
    habilidad: "Torrente",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Raro",
    imagen: "./assets/img/greninja.png",
    sonido: "./assets/sound/greninja.mp3",
    shiny: true,
    imagenShiny: "./assets/img/greninja-shiny.png",
  },

  {
    id: 445,
    nombre: "Garchomp",
    tipo: ["Dragón", "Tierra"],
    altura: 1.9,
    peso: 95.0,
    generacion: 4,
    hp: 108,
    ataque: 130,
    velocidad: 102,
    defensa: 95,
    habilidad: "Velo Arena",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Raro",
    imagen: "./assets/img/garchomp.png",
    sonido: "./assets/sound/garchomp.mp3",
    shiny: true,
    imagenShiny: "./assets/img/garchomp-shiny.png",
  },

  {
    id: 150,
    nombre: "Mewtwo",
    tipo: ["Psíquico"],
    altura: 2.0,
    peso: 122.0,
    generacion: 1,
    hp: 106,
    ataque: 110,
    velocidad: 130,
    defensa: 90,
    habilidad: "Presión",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Legendario",
    imagen: "./assets/img/mewtwo.png",
    sonido: "./assets/sound/mewtwo.mp3",
    shiny: true,
    imagenShiny: "./assets/img/mewtwo-shiny.png",
  },

  {
    id: 384,
    nombre: "Rayquaza",
    tipo: ["Dragón", "Volador"],
    altura: 7.0,
    peso: 206.5,
    generacion: 3,
    hp: 105,
    ataque: 150,
    velocidad: 95,
    defensa: 90,
    habilidad: "Bucle Aire",
    tieneEvolucion: false,
    evolucion: null,
    nivelEvolucion: null,
    rareza: "Legendario",
    imagen: "./assets/img/rayquaza.png",
    sonido: "./assets/sound/rayquaza.mp3",
    shiny: true,
    imagenShiny: "./assets/img/rayquaza-shiny.png",
  },
];